language: php

before_install:
    - ./go init

script:
    - ./go format-verify
    - ./go strict-types test src
    - ./go lint
    - ./go test

cache:
    directories:
        - vendor
        - node_modules
        - $HOME/.composer
        - $HOME/.cache/yarn
        - /nix

after_success:
    - test "$TRAVIS_BRANCH" = "master" && ./go tag
