language: nix

before_install:
    - sudo mkdir -p /etc/nix
    - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
    - ./go init

script:
    - ./go format-verify
    - ./go strict-types test src
    - ./go lint
    - ./go test

before_cache:
    - mkdir -p $HOME/nix.store
    - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

cache:
    directories:
        - vendor
        - node_modules
        - $HOME/.composer
        - $HOME/.cache/yarn
        - $HOME/nix.store

after_success:
    - 'git remote set-url origin "https://ylixir:$GITHUB_TOKEN@github.com/ylixir/phap.git" > /dev/null 2>&1'
    - '[[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]] && echo Making release && ./go tag || echo Not making release for "$TRAVIS_BRANCH" and pull request "$TRAVIS_PULL_REQUEST"'
