language: php

before_install:
    - ./go init

script:
    - ./go format-verify
    - ./go strict-types test src
    - ./go lint
    - ./go test

cache:
    - vendor
    - node_modules
    - $HOME/.composer
    - /nix
